version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dev-container
    container_name: dev
    restart: always
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /workspace/app
